# Generated by Django 3.1.4 on 2020-12-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_name', models.CharField(max_length=30)),
                ('bb_phone_no', models.CharField(max_length=15)),
                ('bb_address', models.CharField(max_length=40)),
                ('bb_Email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=25)),
                ('d_age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('d_address', models.CharField(max_length=40, null=True)),
                ('d_dob', models.DateField()),
                ('d_phone_no', models.CharField(max_length=15)),
                ('med_hist', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30, unique=True)),
                ('h_phone_no', models.CharField(max_length=15)),
                ('h_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.CharField(max_length=10)),
                ('bld_typ_req', models.CharField(max_length=3)),
                ('recipient_name', models.CharField(max_length=20)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('e_phone_no', models.CharField(max_length=15)),
                ('e_Address', models.CharField(max_length=40)),
                ('e_email', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=20)),
                ('bb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodbank')),
            ],
        ),
        migrations.CreateModel(
            name='blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bld_type', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bld_qty', models.CharField(max_length=15)),
                ('bb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodbank')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.donor')),
            ],
        ),
    ]
