# Generated by Django 3.1.4 on 2020-12-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('bld_typ_req', models.CharField(max_length=3)),
                ('recipient_name', models.CharField(max_length=20)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='blood',
            name='bld_qty',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
